version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: "npm-packages"
          paths: -/src/node-modules
      - run: npm run lint
      - run:
          command: echo "failed step before"
          when: on_fail

  test:
    docker:
      -image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm run test
      - run:
          command: echo "failed step before"
          when: on_fail
workflows:
  build-test-analyze-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
